# Generated by Django 3.0.6 on 2020-06-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, null=True)),
                ('user_type_id', models.IntegerField(choices=[(1, '超级用户'), (2, 'VIP用户'), (3, '普通用户')], default=1)),
                ('user_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.UserGroup')),
            ],
        ),
    ]
